/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ICard,
} from './components/woolies-card/woolies-card';
import {
  ICard as ICard1,
} from './components/woolies-card/woolies-card';
import {
  TypographyVariant,
} from './components/woolies-typography/woolies-typography';

export namespace Components {
  interface WooliesApp {}
  interface WooliesBtn {}
  interface WooliesCard {
    'card': ICard;
  }
  interface WooliesCardList {
    'cards': ICard[];
    'special': boolean;
    'title': string;
  }
  interface WooliesHeader {}
  interface WooliesTypography {
    'variant': TypographyVariant;
  }
}

declare global {


  interface HTMLWooliesAppElement extends Components.WooliesApp, HTMLStencilElement {}
  var HTMLWooliesAppElement: {
    prototype: HTMLWooliesAppElement;
    new (): HTMLWooliesAppElement;
  };

  interface HTMLWooliesBtnElement extends Components.WooliesBtn, HTMLStencilElement {}
  var HTMLWooliesBtnElement: {
    prototype: HTMLWooliesBtnElement;
    new (): HTMLWooliesBtnElement;
  };

  interface HTMLWooliesCardElement extends Components.WooliesCard, HTMLStencilElement {}
  var HTMLWooliesCardElement: {
    prototype: HTMLWooliesCardElement;
    new (): HTMLWooliesCardElement;
  };

  interface HTMLWooliesCardListElement extends Components.WooliesCardList, HTMLStencilElement {}
  var HTMLWooliesCardListElement: {
    prototype: HTMLWooliesCardListElement;
    new (): HTMLWooliesCardListElement;
  };

  interface HTMLWooliesHeaderElement extends Components.WooliesHeader, HTMLStencilElement {}
  var HTMLWooliesHeaderElement: {
    prototype: HTMLWooliesHeaderElement;
    new (): HTMLWooliesHeaderElement;
  };

  interface HTMLWooliesTypographyElement extends Components.WooliesTypography, HTMLStencilElement {}
  var HTMLWooliesTypographyElement: {
    prototype: HTMLWooliesTypographyElement;
    new (): HTMLWooliesTypographyElement;
  };
  interface HTMLElementTagNameMap {
    'woolies-app': HTMLWooliesAppElement;
    'woolies-btn': HTMLWooliesBtnElement;
    'woolies-card': HTMLWooliesCardElement;
    'woolies-card-list': HTMLWooliesCardListElement;
    'woolies-header': HTMLWooliesHeaderElement;
    'woolies-typography': HTMLWooliesTypographyElement;
  }
}

declare namespace LocalJSX {
  interface WooliesApp {}
  interface WooliesBtn {}
  interface WooliesCard {
    'card'?: ICard;
    'onAddToCard'?: (event: CustomEvent<ICard>) => void;
  }
  interface WooliesCardList {
    'cards'?: ICard[];
    'special'?: boolean;
    'title'?: string;
  }
  interface WooliesHeader {}
  interface WooliesTypography {
    'variant'?: TypographyVariant;
  }

  interface IntrinsicElements {
    'woolies-app': WooliesApp;
    'woolies-btn': WooliesBtn;
    'woolies-card': WooliesCard;
    'woolies-card-list': WooliesCardList;
    'woolies-header': WooliesHeader;
    'woolies-typography': WooliesTypography;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'woolies-app': LocalJSX.WooliesApp & JSXBase.HTMLAttributes<HTMLWooliesAppElement>;
      'woolies-btn': LocalJSX.WooliesBtn & JSXBase.HTMLAttributes<HTMLWooliesBtnElement>;
      'woolies-card': LocalJSX.WooliesCard & JSXBase.HTMLAttributes<HTMLWooliesCardElement>;
      'woolies-card-list': LocalJSX.WooliesCardList & JSXBase.HTMLAttributes<HTMLWooliesCardListElement>;
      'woolies-header': LocalJSX.WooliesHeader & JSXBase.HTMLAttributes<HTMLWooliesHeaderElement>;
      'woolies-typography': LocalJSX.WooliesTypography & JSXBase.HTMLAttributes<HTMLWooliesTypographyElement>;
    }
  }
}


